CREATE TABLE `trips` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `version` int(11) NOT NULL DEFAULT '0',
  `starttime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `stoptime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `duration` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `car_id` int(11) NOT NULL,
  `passenger_id` int(11) NOT NULL,
  `tripdistance` double NOT NULL,
  `cost` double NOT NULL DEFAULT '0',
  `tip` int(11) NOT NULL DEFAULT '0',
  `totalcost` double NOT NULL DEFAULT '0',
  `ratingtodriver` int(11) NOT NULL DEFAULT '0',
  `ratingtopassenger` int(11) NOT NULL DEFAULT '0',
  `feedbacktodriver` text,
  `feedbacktopassenger` text,
  `created` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `modified` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `car_id_idx` (`car_id`),
  KEY `fk_passenger_id_idx` (`passenger_id`),
  CONSTRAINT `fk_car_id` FOREIGN KEY (`car_id`) REFERENCES `cars` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_passenger_id` FOREIGN KEY (`passenger_id`) REFERENCES `passengers` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
